In [2]:
import pandas as pd
import os

In [ ]:
directory = r'..\EvolveTest'
dms = 'DMS_tests.xlsx'
dms_path = os.path.join(directory,dms)
seq_names = "variant"
dataset =  'HA-H1N1'
exp_name ="doud"
renaming = {seq_names : "seq_id", exp_name: "activity"}
renamed_xlsx = os.path.join(directory,'DMS_data',(dataset+"_"+exp_name+"_DMS.xlsx"))
df = pd.read_excel(dms_path,sheet_name=dataset)
df = df[[seq_names,exp_name]]
df =df.rename(columns=renaming)
df = df.dropna()\
    .to_excel(renamed_xlsx,index=False)
display(df)

None

In [15]:
import os
import pandas as pd
directory = r'..\EvolveTest'
dms = 'Zikv_E.xlsx'
dms_path = os.path.join(directory,dms)
seq_names = "variant"
dataset = 'zika'
exp_name ="fitness"
renaming = {seq_names : "seq_id", exp_name: "activity"}
renamed_xlsx = os.path.join(directory,'DMS_data',(dataset+
                                        "_"+exp_name+
                                        "_dms.xlsx"))
#df = pd.read_csv(dms_path)
df = pd.read_excel(dms_path,
                   #sheet_name='MAPK1'
                   )
df = df[[seq_names,exp_name]]
df =df.rename(columns=renaming)
df = df.dropna()\
    .to_excel(renamed_xlsx,index=False)
display(df)

None

In [12]:
import os
import pandas as pd
directory = r'..\EvolveTest'
dms = 'DMS_data'
dms_path = os.path.join(directory,dms)
seq_names = "variant"
dataset = 'amiE'
exp_name ="propi"
renamed_xlsx = os.path.join(directory,'DMS_data',(dataset+
                                        "_"+exp_name+
                                        "_dms.xlsx"))
#df = pd.read_csv(dms_path)
df = pd.read_excel(renamed_xlsx)
df['activity'] = df['activity'] + 1
df.to_excel(renamed_xlsx,index=False)
print(df)

     seq_id  activity
0       S9I    1.6352
1       S9C    1.6272
2       H3I    1.6016
3       S9H    1.5562
4       H3V    1.5497
...     ...       ...
6286  C139E   -3.9792
6287  F223E   -4.7994
6288  C178L   -5.6954
6289  N219E   -9.0000
6290  A221F   -9.0000

[6291 rows x 2 columns]

In [75]:
for index, column in enumerate(df.columns):
    if index == 0:
        continue
    renaming = {seq_names : "seq_id",column: "activity"}
    print(column)
    renamed_xlsx = os.path.join(directory,(dataset+"_"+column+"_"+dms))
    new_df = df[[seq_names,column]]
    display(new_df)
    new_df = new_df.rename(columns=renaming)
    display(new_df)
    new_df = new_df.dropna()\
        .to_excel(renamed_xlsx,index=False)

Ndes

                      seq_id      Ndes
0                      H114F  1.607427
1                       H67E  0.962030
2                       E78Q  1.561298
3                       A74I  1.049669
4                       H67K  0.840586
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  3.306708
17429    H67T_H70F_M89F_V96F  2.371787

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  1.607427
1                       H67E  0.962030
2                       E78Q  1.561298
3                       A74I  1.049669
4                       H67K  0.840586
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  3.306708
17429    H67T_H70F_M89F_V96F  2.371787

[17430 rows x 2 columns]

4Hy

                      seq_id       4Hy
0                      H114F  1.334331
1                       H67E  0.857881
2                       E78Q  2.150390
3                       A74I  1.139884
4                       H67K  0.948559
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  2.397370
17427    H67E_A74V_M89L_V96L  1.547270
17428   H70L_M89L_L92T_L113F  1.255487
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  1.334331
1                       H67E  0.857881
2                       E78Q  2.150390
3                       A74I  1.139884
4                       H67K  0.948559
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  2.397370
17427    H67E_A74V_M89L_V96L  1.547270
17428   H70L_M89L_L92T_L113F  1.255487
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

Nar

                      seq_id       Nar
0                      H114F  3.222129
1                       H67E  1.501787
2                       E78Q  1.538950
3                       A74I  1.651650
4                       H67K  1.547288
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  1.973255
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  3.222129
1                       H67E  1.501787
2                       E78Q  1.538950
3                       A74I  1.651650
4                       H67K  1.547288
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  1.973255
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

EllA

                      seq_id      EllA
0                      H114F  1.205477
1                       H67E  0.948620
2                       E78Q  0.692447
3                       A74I  0.820646
4                       H67K  1.035227
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  1.205477
1                       H67E  0.948620
2                       E78Q  0.692447
3                       A74I  0.820646
4                       H67K  1.035227
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

Phlo

                      seq_id      Phlo
0                      H114F  3.243579
1                       H67E  1.295898
2                       E78Q  1.808748
3                       A74I  1.442031
4                       H67K  1.380574
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  3.243579
1                       H67E  1.295898
2                       E78Q  1.808748
3                       A74I  1.442031
4                       H67K  1.380574
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

Tam

                      seq_id       Tam
0                      H114F  1.510942
1                       H67E  1.257235
2                       E78Q  1.833116
3                       A74I  1.407069
4                       H67K  0.913515
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  1.510942
1                       H67E  1.257235
2                       E78Q  1.833116
3                       A74I  1.407069
4                       H67K  0.913515
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

Nal

                      seq_id       Nal
0                      H114F  0.942448
1                       H67E  0.942233
2                       E78Q  1.116025
3                       A74I  1.130822
4                       H67K  0.893472
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  0.942448
1                       H67E  0.942233
2                       E78Q  1.116025
3                       A74I  1.130822
4                       H67K  0.893472
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

End

                      seq_id       End
0                      H114F  2.063367
1                       H67E  0.894185
2                       E78Q  2.630031
3                       A74I  1.120176
4                       H67K  0.945068
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  2.063367
1                       H67E  0.894185
2                       E78Q  2.630031
3                       A74I  1.120176
4                       H67K  0.945068
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

Quin

                      seq_id      Quin
0                      H114F  2.178863
1                       H67E  1.835328
2                       E78Q  1.490362
3                       A74I  1.470115
4                       H67K  1.429230
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F  2.178863
1                       H67E  1.835328
2                       E78Q  1.490362
3                       A74I  1.470115
4                       H67K  1.429230
...                      ...       ...
17425  L93I_V96F_L113A_H114Y  0.000000
17426   H70L_M89L_L92M_L113F  0.000000
17427    H67E_A74V_M89L_V96L  0.000000
17428   H70L_M89L_L92T_L113F  0.000000
17429    H67T_H70F_M89F_V96F  0.000000

[17430 rows x 2 columns]

num_mut

                      seq_id  num_mut
0                      H114F      NaN
1                       H67E      NaN
2                       E78Q      NaN
3                       A74I      NaN
4                       H67K      NaN
...                      ...      ...
17425  L93I_V96F_L113A_H114Y      NaN
17426   H70L_M89L_L92M_L113F      NaN
17427    H67E_A74V_M89L_V96L      NaN
17428   H70L_M89L_L92T_L113F      NaN
17429    H67T_H70F_M89F_V96F      NaN

[17430 rows x 2 columns]

                      seq_id  activity
0                      H114F       NaN
1                       H67E       NaN
2                       E78Q       NaN
3                       A74I       NaN
4                       H67K       NaN
...                      ...       ...
17425  L93I_V96F_L113A_H114Y       NaN
17426   H70L_M89L_L92M_L113F       NaN
17427    H67E_A74V_M89L_V96L       NaN
17428   H70L_M89L_L92T_L113F       NaN
17429    H67T_H70F_M89F_V96F       NaN

[17430 rows x 2 columns]

In [14]:
#df.rename(columns={'Unnamed: 0': 'seq_id'})[['seq_id', 'embedding']]\
#    .to_csv(embeddings_path, index=False)