In [1]:
import pandas as pd
import os

In [7]:
directory = r'..\EvolveTest'
dms = 'bla_DMS_amp_625_(b)_DMS_tests.xlsx'
dms_path = os.path.join(directory,'DMS_data',dms)
embeddings = 'TEM_esm1b_t33_650M_UR50S.csv'
def clean_embeddings_df(dms_df,embeddings_df): 
    clean_embeddings_df = pd.merge(embeddings_df,dms_df,on='seq_id',how='inner')
    clean_embeddings_df = clean_embeddings_df[['seq_id','embedding']]
    return clean_embeddings_df

In [8]:
clean_embeddings_df(directory,dms,dms_path,embeddings)

     seq_id  activity
0      H24A  0.003888
1      H24C  0.018871
2      H24D  0.006743
3      H24E -0.020436
4      H24F  0.016190
...     ...       ...
4973  W286R -1.902061
4974  W286S -2.347502
4975  W286T -2.070245
4976  W286V -1.866516
4977  W286Y -0.043875

[4978 rows x 2 columns]

     seq_id                                          embedding
0     A123C  [0.0996927917003631, -0.0208381507545709, -0.1...
1     A123D  [0.0967179834842681, -0.024486981332302, -0.12...
2     A123E  [0.0970067009329795, -0.0243250261992216, -0.1...
3     A123F  [0.0973752588033676, -0.0210936479270458, -0.1...
4     A123G  [0.098469965159893, -0.0228642839938402, -0.12...
...     ...                                                ...
5429   Y95R  [0.102418728172779, -0.0222278330475091, -0.12...
5430   Y95S  [0.1033475622534751, -0.0210307296365499, -0.1...
5431   Y95T  [0.1043880730867385, -0.0220085456967353, -0.1...
5432   Y95V  [0.104971095919609, -0.0240654256194829, -0.13...
5433   Y95W  [0.0996735692024231, -0.0201044641435146, -0.1...

[5434 rows x 2 columns]

     seq_id                                          embedding
0     A123C  [0.0996927917003631, -0.0208381507545709, -0.1...
1     A123D  [0.0967179834842681, -0.024486981332302, -0.12...
2     A123E  [0.0970067009329795, -0.0243250261992216, -0.1...
3     A123F  [0.0973752588033676, -0.0210936479270458, -0.1...
4     A123G  [0.098469965159893, -0.0228642839938402, -0.12...
...     ...                                                ...
4973   Y95R  [0.102418728172779, -0.0222278330475091, -0.12...
4974   Y95S  [0.1033475622534751, -0.0210307296365499, -0.1...
4975   Y95T  [0.1043880730867385, -0.0220085456967353, -0.1...
4976   Y95V  [0.104971095919609, -0.0240654256194829, -0.13...
4977   Y95W  [0.0996735692024231, -0.0201044641435146, -0.1...

[4978 rows x 2 columns]

In [72]:
directory = r'..\EvolveTest'
dms = 'NIshi_ttgr_filt.xlsx'
dms_path = os.path.join(directory,dms)
seq_names = "seq_id"
dataset = 'ttgr'
exp_name ="DMS_amp_625_(b)"
renaming = {seq_names : "seq_id", exp_name: "activity"}
renamed_xlsx = os.path.join(directory,'DMS_data',(dataset+"_"+exp_name+"_"+dms))
df = pd.read_excel(dms_path)
#df = df[[seq_names,exp_name]]
#df =df.rename(columns=renaming)
#df = df.dropna()\
#    .to_excel(renamed_xlsx,index=False)
display(df)

,seq_id,Ndes,4Hy,Nar,EllA,Phlo,Tam,Nal,End,Quin,num_mut
0,H114F,1.607427,1.334331,3.222129,1.205477,3.243579,1.510942,0.942448,2.063367,2.178863,NaN
1,H67E,0.962030,0.857881,1.501787,0.948620,1.295898,1.257235,0.942233,0.894185,1.835328,NaN
2,E78Q,1.561298,2.150390,1.538950,0.692447,1.808748,1.833116,1.116025,2.630031,1.490362,NaN
3,A74I,1.049669,1.139884,1.651650,0.820646,1.442031,1.407069,1.130822,1.120176,1.470115,NaN
4,H67K,0.840586,0.948559,1.547288,1.035227,1.380574,0.913515,0.893472,0.945068,1.429230,NaN
...,...,...,...,...,...,...,...,...,...,...,...
17425,L93I_V96F_L113A_H114Y,0.000000,0.000000,1.973255,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
17426,H70L_M89L_L92M_L113F,0.000000,2.397370,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
17427,H67E_A74V_M89L_V96L,0.000000,1.547270,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
17428,H70L_M89L_L92T_L113F,3.306708,1.255487,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
17429,H67T_H70F_M89F_V96F,2.371787,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN

In [ ]:
for index, column in enumerate(df.columns):
    if index == 0:
        continue
    renaming = {seq_names : "seq_id",column: "activity"}
    print(column)
    renamed_xlsx = os.path.join(directory,(dataset+"_"+column+"_"+dms))
    new_df = df[[seq_names,column]]
    display(new_df)
    new_df = new_df.rename(columns=renaming)
    display(new_df)
    new_df = new_df.dropna()\
        .to_excel(renamed_xlsx,index=False)

In [20]:
embeddings_df = pd.read_csv(r'..\EvolveTest\rubisco\embeddings\rubisco_esmc_600m_WT.csv')
logits_df = pd.read_csv(r'..\EvolveTest\rubisco\embeddings\logits_rubisco_wt_melted.csv')
clean_logits_df = pd.merge(logits_df, embeddings_df, on='seq_id', how='inner')
logits_WTM_df = clean_logits_df.sort_values('wt_marginal', ascending=False)
logits_nWT_df = clean_logits_df.sort_values('probability', ascending=False)
#display(clean_logits_df)
display(logits_WTM_df)
#display(logits_nWT_df)
WTM_vars = logits_WTM_df.head(8)
nWT_vars = logits_nWT_df.head(8)
initial_round_activity = pd.concat([WTM_vars,nWT_vars])
display(initial_round_activity)

,seq_id,probability,locus,wt_probability,wt_marginal,seq,embedding
2141,Q113F,6.093750e-01,113,0.002823,2.158703e+02,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[5.021955803385936e-05, -0.004060470964759588,..."
1523,T81V,5.195312e-01,81,0.006531,7.955140e+01,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-0.00010325664334231988, -0.00437394389882683..."
2780,W147R,3.203125e-01,147,0.004578,6.997333e+01,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00022016339062247425, -0.004183726850897074..."
7590,I400P,8.671875e-01,400,0.015869,5.464615e+01,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00013070643763057888, -0.004583023954182863..."
2142,Q113Y,1.445312e-01,113,0.002823,5.120000e+01,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.000125856589875184, -0.004127630963921547, ..."
...,...,...,...,...,...,...,...
3681,E194Y,7.636845e-08,194,1.000000,7.636845e-08,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.0002891129697673023, -0.0030183386988937855..."
3654,D193R,7.497147e-08,193,1.000000,7.497147e-08,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00043437202111817896, -0.003834327217191457..."
3680,E194F,6.845221e-08,194,1.000000,6.845221e-08,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.0002768775448203087, -0.003154994221404195,..."
3684,E194W,5.261973e-08,194,1.000000,5.261973e-08,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.0004697467666119337, -0.0032701268792152405..."
3627,K191W,3.539026e-08,191,1.000000,3.539026e-08,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00011979948612861335, -0.003884621895849704..."

,seq_id,probability,locus,wt_probability,wt_marginal,seq,embedding
2141,Q113F,0.609375,113,0.002823,215.870270,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[5.021955803385936e-05, -0.004060470964759588,..."
1523,T81V,0.519531,81,0.006531,79.551402,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-0.00010325664334231988, -0.00437394389882683..."
2780,W147R,0.320312,147,0.004578,69.973333,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00022016339062247425, -0.004183726850897074..."
7590,I400P,0.867188,400,0.015869,54.646154,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00013070643763057888, -0.004583023954182863..."
2142,Q113Y,0.144531,113,0.002823,51.200000,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.000125856589875184, -0.004127630963921547, ..."
5967,Q315A,0.337891,315,0.007019,48.139130,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-3.776537050725892e-05, -0.004326325841248035..."
1274,D68A,0.486328,68,0.011414,42.609626,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-0.0002000689273700118, -0.00390983372926712,..."
5339,N282L,0.209961,282,0.004944,42.469136,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[4.233257641317323e-05, -0.004427737090736628,..."
7590,I400P,0.867188,400,0.015869,54.646154,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00013070643763057888, -0.004583023954182863..."
5372,F283Y,0.812500,283,0.109863,7.395556,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[5.2761064580408856e-05, -0.00424928916618228,..."
3339,F176Y,0.808594,176,0.140625,5.750000,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-5.218584192334674e-05, -0.004129886627197266..."
7343,N387D,0.789062,387,0.073242,10.773333,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-0.00016442932246718556, -0.00463038124144077..."
1024,N54W,0.726562,54,0.019287,37.670886,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[0.00018126206123270094, -0.004672667477279901..."
2318,M123L,0.683594,123,0.043701,15.642458,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-7.529926369898021e-05, -0.004150360822677612..."
3900,D206E,0.683594,206,0.196289,3.482587,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[-8.561214053770527e-05, -0.004126803483814001..."
3936,I208V,0.660156,208,0.166992,3.953216,MDQSSRYVNLALKEEDLIAGGEHVLCAYIMKPKAGYGYVATAAHFA...,"[8.811920270090923e-05, -0.0043348465114831924..."