In [2]:
import pandas as pd

deltanonalactone_seq_ids = '''Y146A_Y255T
Y220H_Y255M
Y146L_Y255T
Y255T_Q296H
F80A_Y255R
Y255T_E259S
Y146S_Y255T
Y255T_Q296R
Y146C_Y255T
Y220H_Y255T
Q75R_Y255T
Y255T_Q296C
Y146I_Y255T
Q123D_Y255R
Y146S_Y255M
T52G_Y255T
Y146M_Y255T
Y255M_E259S
Y146V_Y255T
Y255M_L280R
Y146I_Y255M
Y255T_H279K
Y146T_Y255T
T215R_Y255L'''.split('\n')

ethylvalerolactam_seq_ids = '''Q123D_Q296H
Q123D_L241I
Q45S_Q123D
Q123D_A309P
Q123D_A187I
Q123D_Q155S
Q63A_E218I
Q123D_P254G
Q99R_Q123D
Q123D_H318D
Q123D_Q303R
Q63V_Q123D
Q123D_Q264K
Q12D_Q123D
Q123D_T190L
Q123D_G237K
Q123D_Q155T
D25R_Q63A
P2I_Q123D
Q45R_Q123D
Q63A_Q296H
Q123D_V312Y
Q16A_Q123D
W10V_Q123D'''.split('\n')

cyclohexanone_seq_ids = '''K137A_Y255L
K144A_Y255L
E218R_Y255L
K137P_Y255L
E218L_Y255T
K144D_Y255L
E218M_Y255L
E218R_Y255T
K144A_Y255T
Y255L_A309P
E218I_Y255T
K144E_Y255M
G237R_Y255T
E218R_Y255M
Y255L_Q296H
Y255M_A309P
K144E_Y255L
Y255M_Q296H
Y255T_A309P
P29R_Y255L
I252G_Y255M
N139A_Y255L
K144D_Y255M
E218T_Y255T'''.split('\n')

N_TO_GET = 16

first_few_of_each = list(set(
    deltanonalactone_seq_ids[:N_TO_GET] +
    ethylvalerolactam_seq_ids[:N_TO_GET] +
    cyclohexanone_seq_ids[:N_TO_GET]
))

for seq_id in first_few_of_each:
    print(seq_id)
print(len(first_few_of_each))

Y255T_Q296R
Q123D_H318D
K144A_Y255L
Q123D_Q264K
Y255L_A309P
Y146I_Y255T
Q123D_P254G
Y146C_Y255T
Q123D_Q303R
Q123D_Q155S
Q123D_A309P
Q63V_Q123D
Q12D_Q123D
Y255M_A309P
Q123D_T190L
K137P_Y255L
Y255T_Q296H
E218M_Y255L
G237R_Y255T
Y146S_Y255M
F80A_Y255R
Q123D_Y255R
Y146S_Y255T
Q123D_L241I
E218R_Y255L
T52G_Y255T
E218R_Y255T
Y220H_Y255T
Q123D_Q296H
K144E_Y255M
Y220H_Y255M
E218L_Y255T
K144A_Y255T
Y146L_Y255T
Y255T_E259S
Q123D_G237K
Q99R_Q123D
E218I_Y255T
K137A_Y255L
Y146A_Y255T
Y255L_Q296H
Q75R_Y255T
Y255T_Q296C
Q45S_Q123D
Q63A_E218I
K144D_Y255L
E218R_Y255M
Q123D_A187I
48

In [17]:
seq_id_map = pd.read_excel('notebooks/jacob/round2/250604_round2_seq_ids.xlsx')

def index_to_well(index: int) -> str:
    return f"{'ABCDEFGH'[index // 12]}{index % 12 + 1}"
assert index_to_well(0) == 'A1', index_to_well(0)
assert index_to_well(11) == 'A12'
assert index_to_well(12) == 'B1'
assert index_to_well(23) == 'B12'

important_ap_oplr_seqs = seq_id_map[seq_id_map.seq_id.isin(first_few_of_each) & (seq_id_map.campaign_id == 'AP_OplR')].copy()

important_ap_oplr_seqs['well'] = important_ap_oplr_seqs.teselagen_plasmid_id.apply(lambda tid: index_to_well(int(tid[-4:]) - 1))

important_ap_oplr_seqs[['campaign_id', 'seq_id', 'teselagen_plasmid_id', 'well']].to_csv('notebooks/jacob/round2/250710_important_ap_oplr_mutants.csv', index=False)

In [18]:
len(important_ap_oplr_seqs)

48

In [19]:
seq_id_map

,campaign_id,design_id,seq_id,teselagen_plasmid_id,base_seq_id,new_allele_id
0,TY_Pop2,TY_Pop2_R2,Q70K,TY_Pop2_R2_0001,WT,Q70K
1,TY_Pop2,TY_Pop2_R2,I182V,TY_Pop2_R2_0002,WT,I182V
2,TY_Pop2,TY_Pop2_R2,D186N,TY_Pop2_R2_0003,WT,D186N
3,TY_Pop2,TY_Pop2_R2,R200K,TY_Pop2_R2_0004,WT,R200K
4,TY_Pop2,TY_Pop2_R2,K234E,TY_Pop2_R2_0005,WT,K234E
...,...,...,...,...,...,...
236,SK_Art,SK_Art_R2,Y100K_Y229Q,SK_Art_R2_0008,Y100K,Y229Q
237,SK_Art,SK_Art_R2,Y100K_G243D,SK_Art_R2_0009,Y100K,G243D
238,SK_Art,SK_Art_R2,Y100L_Y229D,SK_Art_R2_0010,Y100L,Y229D
239,SK_Art,SK_Art_R2,Y100L_Y229E,SK_Art_R2_0011,Y100L,Y229E
240,SK_Art,SK_Art_R2,S239E_R262A,SK_Art_R2_0012,S239E,R262A

In [22]:
seq_id_map[seq_id_map.campaign_id == 'AP_OplR'].shape

(96, 6)

In [23]:
seq_id_map

,campaign_id,design_id,seq_id,teselagen_plasmid_id,base_seq_id,new_allele_id
0,TY_Pop2,TY_Pop2_R2,Q70K,TY_Pop2_R2_0001,WT,Q70K
1,TY_Pop2,TY_Pop2_R2,I182V,TY_Pop2_R2_0002,WT,I182V
2,TY_Pop2,TY_Pop2_R2,D186N,TY_Pop2_R2_0003,WT,D186N
3,TY_Pop2,TY_Pop2_R2,R200K,TY_Pop2_R2_0004,WT,R200K
4,TY_Pop2,TY_Pop2_R2,K234E,TY_Pop2_R2_0005,WT,K234E
...,...,...,...,...,...,...
236,SK_Art,SK_Art_R2,Y100K_Y229Q,SK_Art_R2_0008,Y100K,Y229Q
237,SK_Art,SK_Art_R2,Y100K_G243D,SK_Art_R2_0009,Y100K,G243D
238,SK_Art,SK_Art_R2,Y100L_Y229D,SK_Art_R2_0010,Y100L,Y229D
239,SK_Art,SK_Art_R2,Y100L_Y229E,SK_Art_R2_0011,Y100L,Y229E
240,SK_Art,SK_Art_R2,S239E_R262A,SK_Art_R2_0012,S239E,R262A